### ISSUE TITLE
Sentinel-cpp Roadmap Question

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-cpp#8]
Hi, Recently we are investigating the flow control framework. May I ask about the sentinel-CPP version roadmap? When is it available?

Tks

**Comment by sczyh30** [comment]
Hi, we're planning to release a beta version in June, which consists of basic statistic, metrics, and rate limiting features.

**Comment by louyuting** [comment]
As far as I understand, the beta version is for single-machine flow control?

**Comment by sczyh30** [comment]
> As far as I understand, the beta version is for single-machine flow control?

Yes, the beta version is for local flow control. We have a token server implementation in Java for cluster flow control, but for Sentinel C++ we need to work on the C++ token client to communicate with the token server. Further plans: https://github.com/alibaba/Sentinel/issues/741

Discussions and contributions are welcomed.
